#!/bin/bash
# Script to build seturi file.  
# Run this to add custom/modified Malleable C2 profiles into the buildredteam.sh
# This will allow automation of starting a CS teamserver or HAProxy redirector
C2path="/root/cobaltstrike/Malleable-C2-Profiles"
seturifile="/root/scripts/seturi.txt"
echo "#seturi.txt generated by makeseturi.sh" > $seturifile
echo "#Contains the Malleable C2 profiles 'set uri' variablesi" >> $seturifile
echo "#This file is used by buildredteam.sh when setting up HAProxy redirection" >> $seturifile
cd $C2path
for i in `ls` 
do
  for j in `ls $i/*` 
  do
    grep "set uri" $C2path/$j | while read k
    do 
      C2foldername=`echo $j | sed 's/\//,/'`
      for m in `echo $k | awk -F '"' '{print$2}'`
      do
        echo $C2foldername,$m >> $seturifile
      done
    done
  done
done
